### ISSUE TITLE
Assigned bug list is not displayed for each entry.

### ISSUE THREAD

**Issue by kkdeep** [MozillaIndia/leaderboard#62]
The assigned bug's link is not working for each entry. By looking at the app.js it seems that its linking the bugzilla's search query through email id and so it must work for each entry.

**Comment by debloper** [comment]
Please explain a bit better. Not clear to me.

**Comment by kkdeep** [comment]
What i meant was if you click on _Optimiser_'s total assigned bugs it returns the bugs assigned to him whereas for say _sshagarwal_ its not returning anything.
I checked again and its not a bug i guess since some email id's are not yet provided so its returning empty response.

**Comment by debloper** [comment]
Yes, the ones who have not given us their email IDs with consent, we are not allowed to display that publicly.
